spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db?ApplicationName=${spring.application.name}&stringtype=unspecified
    username: test
    password: test
transmetrics:
  date-time-api:
    host: https://api.xmltime.com
    accesskey: fill_me_out
    secret_key: fill_me_out