spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5432}/test-db?ApplicationName=${spring.application.name}&stringtype=unspecified
    username: ${TEST_DB_USERNAME:test}
    password: ${TEST_DB_PASSWORD:test}
transmetrics:
  date-time-api:
    host: https://api.xmltime.com
    accesskey: ${DATE_TIME_API_ACCESS_KEY:fill_me_out}
    secret_key: ${DATE_TIME_API_SECRET_KEY:fill_me_out}
